name: "Build, Secure & Release"
on:
  push:
    branches: [ "main" ]

jobs:
  update-pack-version:
    if: "startsWith(github.event.head_commit.message, 'release')"
    name: "Update pack version, Secure pack & Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run the version change script
        run: "php increase-pack-version.php"


      - name: "Get data"
        id: metadata
        run: |
          echo ::set-output name=VERSION::$(php -r 'echo implode(".", json_decode(getcwd() . DIRECTORY_SEPARATOR . "pack/manifest.json", true)["header"]["version"]))')
          echo ::set-output name=DESCRIPTION::$(php -r 'json_decode(getcwd() . DIRECTORY_SEPARATOR . "pack/manifest.json", true)["header"]["description"]);')
          echo ::set-output name=NAME::$(php -r 'json_decode(getcwd() . DIRECTORY_SEPARATOR . "pack/manifest.json", true)["header"]["name"]);')


      - name: "Commit files"
        run: |
          git config --local user.name "xxAROX"
          git config --local user.email "arox.email.0@gmail.com"
          git add pack/manifest.json
          git commit -m "Updated pack version"



      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true
      - name: "Secure pack"
        run: |
          chmod +x index.php
          php index.php

      - name: "Create Release"
        run: |
          cd pack/
          zip -r ../Resource-Pack.zip *
          echo "Done!"

      - name: "Create Release secured"
        run: |
          cd output/
          zip -r ../Resource-Pack-secured.zip *
          echo "Done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.metadata.outputs.VERSION }}"
          prerelease: false
          title: "Release v${{ steps.metadata.outputs.VERSION }}"
          files: |
            Resource-Pack.zip
            Resource-Pack-secured.zip
